### ISSUE TITLE
website not updated since Oct 6 with outdated doxygen

### ISSUE THREAD

**Issue by MrMormon** [dneg/openvdb_points_dev#22]
Instead of 1.6.1, openvdb.org uses 1.8.8.

**Comment by danrbailey** [comment]
Hi Joshua, apologies, we'll get this updated soon. 

I was planning on only syncing up the documentation with every release (we're currently working towards 0.2.0), but we should be able to automate something here to ensure it stays always in sync with the master branch. Also, I'll make sure we're building this against a later version of Doxygen, thanks for pointing this out.
